language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: TYT1h+7uFlZAYV5wxgRJbzY5nILvCfSfqVSTvqY474hzbd56ZWUkEpzXa3Fh5gq9na6LfwNmKFuShsJjC8GudtLetRCc3ulivAXFbeIx7/jjAqFvhkb4zUED29w6abdMcjQbiYm1jzwY7gltaUp11JIrcLj1fozEsYSwUh0zhNg=
